### ISSUE TITLE
Uncaught Error: Script error for: /services/routeResolver

### ISSUE THREAD

**Issue by hmendezm** [DanWahlin/CustomerManager#24]
Hi Dan

I try to implement RequireJs in my existing Angularjs App. I did everything that your article mentions but I get the below error.

Do you have any idea why this error?

Uncaught Error: Script error for: /services/routeResolver
http://requirejs.org/docs/errors.html#scripterrormakeError @ require.js:166context.onScriptError @ require.js:1701

**Comment by DanWahlin** [comment]
Very hard to say with only that information especially since it sounds like you're implementing your own version. I'd recommend making sure that your version of the code matches up with what you see in this sample app.
