### ISSUE TITLE
new project throws exception

### ISSUE THREAD

**Issue by jonbonraki** [DanWahlin/CustomerManager#25]
here is the exception

{ [MongoError: connect ECONNREFUSED] name: 'MongoError', message: 'connect EC
REFUSED' } 'Error: connect ECONNREFUSED\n    at exports._errnoException (util
:746:11)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)

my workaround was npm install

**Comment by DanWahlin** [comment]
Make sure you walk through the steps provided in the readme. npm install is one of several required steps.
