### ISSUE TITLE
Login Click keep adding login to the path

### ISSUE THREAD

**Issue by deendayal-garg** [DanWahlin/CustomerManager#30]
As attached in the GIF, when i click on the Login it keeps adding the login path to the existing path and when i login it again redirects me to the login.

![issueangularapp](https://cloud.githubusercontent.com/assets/16479364/13320631/5053b228-dbf0-11e5-9de2-3b0255ee9b13.gif)

**Comment by DanWahlin** [comment]
Thanks for the detailed example. It's not something I have time to look into right now since I've shifted focus to an Angular 2 version of the app. But, if you happen to find the fix and can submit a pull request that'd be great.
