### ISSUE TITLE
ModalService – How to re-use custom controller (assign data when showModal())?

### ISSUE THREAD

**Issue by envision** [DanWahlin/CustomerManager#32]
I would like to re-use a custom controller and modal template. But ModalService's showModal method assigns secondary object (customModalOptions) only when custom controller isn't defined. So when using custom controller you cannot assign data to that controller when triggering the modal?

**Comment by DanWahlin** [comment]
You'd have to modify the code in that case to handle customizations needed. It supports several customizations but certainly not everything.
