### ISSUE TITLE
angular hotkeys

### ISSUE THREAD

**Issue by newzen** [DanWahlin/CustomerManager#33]
Hello,
I'm impressed with your solution. Thanks

I have a little app using angular hotkeys, but have no idea how to inject into controller.

Would you mind, teach me how

Thanks in advance

**Comment by DanWahlin** [comment]
You'll want to post something like that to http://stackoverflow.com (nice community of devs there that may be able to help). The posts here need to be related directly to CustomerManager application issues or features.
